name: "Azure features report"

targets: 
  Azure-Integration:
    type: project
    htmlUrl: https://github.com/github/azure-integration/projects/1
    columnMap:
      Proposed: ["Committed"]          
      Accepted: [
        "In review",                  
        "Release activities"]                     
      In-Progress: ["In Progress"] 
      Done: ["Done"]            

output: "_reports"

reports:
  - name: Azure features report
    title: "{{{ config.name }}} Project Report"
    kind: markdown 
    timezoneOffset: +5.5
    targets: ['Azure-Integration']
    sections:
      - name: "project-in-progress"
        config:
          report-on: 'Feature'
          wip-label-match: "(\\d+)-dev"
